import Head from "next/head";
import Image from "next/image";
import Entry from "../components/Entry";
import Header from "../components/Header";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const ArticleContainer = styled.div`
 /* background-color: #bbb; */
 padding: 80px 0;
`

const Article = styled.article`
  /* @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500;600;700&display=swap'); */
  /* margin: 40px; */
  margin: 0 auto;
  width: 85%;
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
`;

const ArticleTitle = styled.h2`
 font-family: 'Josefin Sans', sans-serif;
 width: 85%;
 margin: 0 auto;
 font-weight: 500;
 font-size: 48px;
 color: #28CC75;
 /* color: #fff; */
 margin-bottom: 20px;
`

export default function Home(props) {
  console.log(props.entries);
  return (
    <div>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap" rel="stylesheet"></link>
      </Head>

      <Header />

      <main>
        <ArticleContainer>
          <ArticleTitle>Works</ArticleTitle>
          <Article>
            {props.entries.contents.map((entry) => {
              return <Entry entry={entry} key={entry.id}></Entry>;
            })}
          </Article>
          {/* <div><img src="../images/sq_300x300.png" alt="" /></div> */}
        </ArticleContainer>
      </main>

      <Footer />
    </div>
  );
}

import { client } from "../utils/client";

export const getStaticProps = async () => {
  const [entries] = await Promise.all([
    client.get({
      endpoint: "entries",

      queries: {
        orders: "-publishedAt",

        offset: 0,

        limit: 10,

        // fields: 'id,title,categories,tags,publishedAt,image,description'
      },
    }),
  ]);

  return {
    props: {
      entries,
    },
  };
};
